# Generated by Django 5.0.2 on 2024-02-18 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_message_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageDetail",
            fields=[
                (
                    "todo_detail_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("detail", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.message"
                    ),
                ),
            ],
        ),
    ]
