# Generated by Django 5.0.2 on 2024-02-18 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_messagedetail_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagedetail",
            name="message",
        ),
    ]
