# Generated by Django 5.0.2 on 2024-02-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_messagedetail_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagedetail",
            name="message",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.message"
            ),
        ),
    ]
