# Generated by Django 5.0.2 on 2024-02-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_messagedetail_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagedetail",
            name="message",
        ),
        migrations.AddField(
            model_name="message",
            name="message_detail",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.messagedetail",
            ),
        ),
    ]
