# Generated by Django 5.0.2 on 2024-02-18 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_message_message_detail_alter_message_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="message_detail",
        ),
        migrations.DeleteModel(
            name="MessageDetail",
        ),
    ]
